### ISSUE TITLE
Shell > Colorful Spring Boot banner

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler-Shell#16]
Add a banner while laucnhing the shell.

Display schemacrawler version (and optionally some system infos) and some cool ASCIIART.

Do this with Spring Boot helper https://toedter.com/2015/12/13/creating-colorful-banners-for-spring-boot-applications/

**Comment by sualeh** [comment]
I have included a banner, but not colorful ASCII art. :-)
